#+TITLE: Among Us - The Other Roles installer

* About this installer
This installer was created to automatically download a given version of the Among Us - The Other Roles Mod.
Created before the mod hosts shipped their own installer as a little side project to automate the process on my old and slow home machine.
This installer is neither fast nor efficient by any means (please bear that in mind :D).
Since some people might be freaked out to run a stranger's shell script I will explain HOW to use this script and WHAT it is doing step by step.


* Setup

Since Windows restricts the usage of any scripts by default, due to security reasons, you will have to do some changes to your configurations before you can use this script.
There are several ways to be able to run a Powershell script.
For the purposes of this Installer script I recommend running the cmdlet
#+begin_src powershell
$ Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine
#+end_src
in an elevated Powershell process.
For further reading on this topic I recommend the offical MS documetation:
[[https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7.2]]

* Installation
** Finding your "common"-folder
Since this installer is made for a Steam Among-Us installation. We will need to find the Steam subfolder "Steam\steamapps\common".
The script tries to find this folder on your C:\ volume:
First it collects all folders/directories named "common"
#+begin_src Powershell
$pathList = (Get-ChildItem -Path C:\ -Filter "common" -Recurse -Directory -ErrorAction SilentlyContinue).Fullname
#+end_src
Second it filters this list of paths to match "steamapps\common".
Since all Steam game folders are subfolders of the "common"-folder this reduces the list to all your Steam games and the desired "common"-folder.
By implementation the desired directory is the first element of the list
#+begin_src Powershell
$steamPath = ($pathList -match "steamapps\\common")[0]
#+end_src

Next you are asked to confirm the found path to your Steam folder.
You can confirm the path by hitting enter or change it by typing the full correct path.
If you changed the path it will be checked whether it is valid by checking if you have a Among Us installation as one of its subfolders.
If the path is found to be invalid you are asked to enter a new path again.
#+begin_src Powershell
Write-Host 'Please confirm that this is your Steam-common folder:

-> ' $steamPath
Write-Host ''
Write-Host If this is the wrong folder please enter the full correct path below!

$valid = $true
do {
    Write-Host ''
    $customPath = Read-Host "Path (Enter to skip)"
    if (-not($customPath -eq '')) {
        $valid = $false
        if ((Test-Path $customPath\'Among Us')) {
            $steamPath = $customPath
            break
        }
        Write-Host $customPath
        Write-Host This path is not valid. Please try again
    }
} while (-not $valid)
#+end_src
** Cloning current Among Us installation
** Finding the latest ToR release
** Downloading the latest or a desired release
** Post cleaning and starting the modded installation
** Optional: Creating shortcut
